# Integration test Quarkus configuration

quarkus:
  datasource:
    devservices:
      enabled: true
  hibernate-orm:
    schema-management:
      strategy: validate
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  flyway:
    migrate-at-start: true
  scheduler:
    enabled: false
